# -*- coding: utf-8 -*-
"""DesafioMl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3QOumqN3pLzKsqdMOiwMMLmtroSMHGA

# **Explicação em etapas do que eu fiz para o desafio proposto**

1. Primeiro eu importei a primeira biblioteca "pandas", logo em seguida eu importei o dataset e depois eu dei uma breve vizualização dos dados
"""

import pandas as pd

df = pd.read_csv('alunos.csv', sep=',')
df.head(5)

"""2. Vi também algumas breves vizualizações sobre as informações do dataset e também a contagem dos valores da futura variavel alvo "**df['aprovado']**"
"""

print(df.info())
print()
print(df.describe())
print()
print(df['aprovado'].value_counts())

"""3. Fiz o pre-processamento dos dados para se adaptar pro modelo que escolhi utilizar, que seria um modelo de classificação"""

df['sexo'] = df['sexo'].map({'M':0,'F':1})
df['nivel_escolar_pais'] = df['nivel_escolar_pais'].map({'fundamental':0,'medio':1,'superior':2})

"""4. Selecionei qual seria as features, nesse caso só tirei as colunas que não tinha impacto pro treinamento e a variavel alvo"""

X = df.drop(['aprovado','id_aluno'], axis=1)
y = df['aprovado']

"""5. Aqui eu importei a função de treino e teste para o treinamento escolhi 30% para um treino e teste padrão"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

"""6. Importei o modelo que eu escolhi para o meu objetivo, definir a quantidade de interações que queria que o modelo fizesse pro treino e fiz o proprio treinamento do modelo"""

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=2000)
model.fit(X_train,y_train)

"""7. Guardei a predição do modelo depois do treinamento"""

y_pred = model.predict(X_test)

"""8. Importei a função de acuracia para avaliar o meu modelo, importei a matrix de confusão para ver de uma forma melhor sobres os valores que o meu modelo acertou e errou, importei a função de tranformar a minha matrix de confusão em algo visual.

    Além dos imports eu utilizei as funções para avaliar e plotei o grafico da matrix
"""

from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

plot_matriz = ConfusionMatrixDisplay(confusion_matrix(y_test,y_pred),display_labels=model.classes_)

print('Acuracia',accuracy_score(y_test,y_pred))
plot_matriz.plot()
plt.show()

"""9. Quis testar em outros modelos(DecisionTreeClassifier) a ponto de comparação, seguindo os passos do primeiro modelo"""

from sklearn.tree import DecisionTreeClassifier

modelo_arvore = DecisionTreeClassifier()
modelo_arvore.fit(X_train, y_train)

y_pred_arvore = modelo_arvore.predict(X_test)

plot_matriz_arvore = ConfusionMatrixDisplay(confusion_matrix(y_test,y_pred_arvore),display_labels=model.classes_)

print('Acuracia Árvore:', accuracy_score(y_test, y_pred_arvore))
plot_matriz_arvore.plot()
plt.show()

"""10. Trouxe um 3º modelo(RandomForestClassifier) para ter uma comparação mais ampla e novamente, seguindo o fluxo dos 2 primeiros"""

from sklearn.ensemble import RandomForestClassifier

modelo_rf = RandomForestClassifier()
modelo_rf.fit(X_train, y_train)

y_pred_rf = modelo_rf.predict(X_test)

plot_matriz_rf = ConfusionMatrixDisplay(confusion_matrix(y_test,y_pred_rf),display_labels=model.classes_)

print("Acuracia RF:", accuracy_score(y_test, y_pred_rf))
plot_matriz_rf.plot()
plt.show()

"""11. Plotei o nivel de importacias das features dos 3 modelos testados"""

importancias_1 = abs(model.coef_[0])

plt.barh(X.columns, importancias_1)
plt.xlabel("Importância")
plt.ylabel("Variáveis")
plt.show()

"""12. Modelo(DecisionTreeClassifier)"""

importancias_2 = modelo_arvore.feature_importances_

plt.barh(X.columns, importancias_2)
plt.xlabel("Importância")
plt.ylabel("Variáveis")
plt.show()

"""13. Modelo(RandomForestClassifier)"""

importancias_3 = modelo_rf.feature_importances_

plt.barh(X.columns, importancias_3)
plt.xlabel("Importância")
plt.ylabel("Variáveis")
plt.show()

"""14. Trouxe novos dados para testar a previsão do modelo na pratica"""

df_novo = pd.read_csv('novos_dados.csv',sep=';')
df_novo

"""15. Fiz um rapida features para fazer a predição com o primeiro modelo"""

X_novo = df_novos.drop(['id_aluno','prvisoes'],axis=1)

prev_novo = model.predict(X_novo)

"""16. Plotei um grafico para analisar a previsão que o modelo fez"""

df_novo['previsoes'] = prev_novo

df_novo['previsoes'] = df_novo['previsoes'].map({0:'Reprovado',1:'Aprovado'})

relatorio_dados_novo = df_novo['previsoes'].value_counts()

plt.pie(relatorio_dados_novo, labels=relatorio_dados_novo.index, autopct='%1.1f%%')
plt.show()

"""17. Repliquei para o outro modelo(DecisionTreeClassifier)"""

prev_novo_arvore = modelo_arvore.predict(X_novo)

df_novo['previsoes'] = prev_novo_arvore

df_novo['previsoes'] = df_novo['previsoes'].map({0:'Reprovado',1:'Aprovado'})

relatorio_dados_novo = df_novo['previsoes'].value_counts()

plt.pie(relatorio_dados_novo, labels=relatorio_dados_novo.index, autopct='%1.1f%%')
plt.show()

"""18. E repliquei para o 3º modelo(RandomForestClassifier)"""

prev_novo_rf = modelo_rf.predict(X_novo)

df_novo['previsoes'] = prev_novo_rf

df_novo['previsoes'] = df_novo['previsoes'].map({0:'Reprovado',1:'Aprovado'})

relatorio_dados_novo = df_novo['previsoes'].value_counts()

plt.pie(relatorio_dados_novo, labels=relatorio_dados_novo.index, autopct='%1.1f%%')
plt.show()

"""19. Conclusão das analises:

    Apesar de utilizar 3 modelos diferentes para o mesmo dataset e os novos dados. A tendencia do surgimento dos alunos aprovados é extremamente baixa e isso se deve pela grande quantidade de faltas, não necessariamente apenas isso, porem é oque mais se destaca diantes de outras features
"""